### ISSUE TITLE
Ubuntu Tests Randomly Fail

### ISSUE THREAD

**Issue by DevOrc** [DevOrc/wgpu-java#15]
The tests are inconsistently failing on the linux jobs with this message:

```
com.noahcharlton.wgpuj.fail.RustFailTest > rustFailTest() FAILED
    org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <com.noahcharlton.wgpuj.fail.RustTestException> but was: <java.lang.NullPointerException>
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2920)
        at com.noahcharlton.wgpuj.fail.RustFailTest.rustFailTest(RustFailTest.java:11)

        Caused by:
        java.lang.NullPointerException: callable is null
            at jnr.ffi.provider.jffi.NativeClosureProxy.getCallable(NativeClosureProxy.java:57)
            at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$0.invoke(Unknown Source)
            at com.noahcharlton.wgpuj.WgpuTest$jnr$ffi$0.rust_fails_test(Native Method)
            at com.noahcharlton.wgpuj.fail.RustFailTest.lambda$rustFailTest$0(RustFailTest.java:11)
            at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
            ... 3 more
```

**Comment by DevOrc** [comment]
Ok now there is another problem

https://github.com/DevOrc/wgpu-java/actions/runs/144232410

**Comment by DevOrc** [comment]
Test has not failed since - so i am going to reclose this issue
